
export const transForm = {
  '总资产周转天数（天）': 'zzczzts',
  '存货周转天数（天）': 'chzzts',
  '应收账款周转天数（天）': 'yszkzzts',
  '总资产周转率（次）': 'toazzl',
  '存货周转率（次）': 'chzzl',
  '应收账款周转率（次）': 'yszkzzl',
  '净资产收益率 (加权)(%)': 'roejq',
  '总资产收益率 (加权)(%)': 'zzcjll',
  '毛利率（%）': 'xsmll',
  '净利率 (%)': 'xsjll',
  '流动比率': 'ld',
  '速动比率': 'sd',
  '现金流量比率': 'xjllb',
  '资产负债率 (%)': 'zcfzl',
  '资本周转率 (%)': 'zbzzl',
  '清算价值比率': 'qsjzbl',
  '利息支付倍数': 'lszfbs',
  '销售利润率': 'xslrl',
  '成本费用利润率': 'cbfylrl',
  '总资产利润率': 'zzclrl',
  '资本金利润率': 'zbjlrl',
  '股东权益利润率': 'gdqylrl'
}
